FROM node:18

# Install dependencies
WORKDIR /app
COPY package*.json ./
RUN npm install

# Install Playwright browsers
RUN npx playwright install --with-deps

# Copy rest of the code
COPY . .

EXPOSE 8080
CMD ["npm", "start"]
